format_version: 3
pipelines:
  sampleJavaWebApp:
    lock_behavior: lockOnFailure
    group: Project
    materials:
      repo: 
       git: https://github.com/PanDeBatalla94/MC_SimpleJavaWebApp.git
       branch: checkstyle 
    stages: 
      - Build:
          jobs:
            building: 
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - "clean"
                      - "assemble"
              artifacts:
                - build:
                    source: build/libs/*.war
                    destination: Build
      - Test:
          jobs:
            Unit_Test: 
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - clean
                      - test
                      - jacocoTestReport
                      - check
              artifacts:
                - build:
                    source: build/reports/tests/test/**/*
                    destination: html
                
                - build:
                    source: build/jacocoHtml/**/*
                    destination: jacoco
                
                - build:
                    source: build/reports/checkstyle/*
                    destination: checkstyle
                
                - test:
                    source: build/reports/findbugs/*
                    destination: findbugs

                - build:
                    source: build/reports/pmd/*
                    destination: pmd

                - test:
                    source: build/test-results/test/*.xml
                    destination: xml
                    
              tabs:
                unit_test: html/index.html
                jacoco: jacoco/index.html
                checkstyle: checkstyle/main.html
                findbugs: findbugs/main.xml
                pmd: pmd/main.html
      - Sonarqube:
          jobs:
            analyzing: 
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - "sonarqube"


 
 
