format_version: 3
pipelines:
  sampleJavaWebApp:
    lock_behavior: lockOnFailure
    group: Project
    materials:
      repo: 
       git: https://github.com/PanDeBatalla94/MC_SimpleJavaWebApp.git #https://github.com/devops-at06/MC_SimpleJavaWebApp.git
       branch: cucumber 
    stages: 
      - Build:
          jobs:
            building: 
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - "clean"
                      - "assemble"
              artifacts:
                - build:
                    source: build/libs/*.war
                    destination: Build_war

      - Test:
          jobs:
            Unit_Test: 
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - test
                      - jacocoTestReport
                      - check
              artifacts:
                - build:
                    source: build/reports/tests/test/**/*
                    destination: html
                
                - build:
                    source: build/jacocoHtml/**/*
                    destination: jacoco
                
                - build:
                    source: build/reports/checkstyle/*
                    destination: checkstyle
                
                - build:
                    source: build/reports/findbugs/*
                    destination: findbugs

                - build:
                    source: build/reports/pmd/*
                    destination: pmd

                - test:
                    source: build/test-results/test/*.xml
                    destination: xml
                    
              tabs:
                unit_test: html/index.html
                jacoco: jacoco/index.html
                checkstyle: checkstyle/main.html
                findbugs: findbugs/main.html
                pmd: pmd/main.html
      - Sonarqube:
          jobs:
            analyzing: 
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - "sonarqube"
      - Deploy:
          jobs:
            deploying: 
              tasks:
                - fetch:
                    stage: Build
                    job: building
                    source: Build_war/
                - exec:
                    command: ./gradlew
                    arguments:
                      - -b
                      - deploy.gradle
                      - deploy
                      - -Pdev_server=10.28.135.235
                      - -Puser_home=/home/go
                      - -Pwar_path=Build_war


      - Cucumber:
          jobs:
            report: 
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - allureReport
              artifacts:
                - build:
                    source: build/reports/allure-report/**/*
                    destination: cucumber                   
              tabs:
                Cucumber: cucumber/index.html

      - Clean:
          jobs:
            cleaning: 
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - "clean"
              



 
 
